### ISSUE TITLE
Fail to install simulaqron v3.0.4  over pip on PyPI

### ISSUE THREAD

**Issue by tai271828** [SoftwareQuTech/SimulaQron#203]
It seems there is an new releases of SimulaQron, v3.0.4 on PyPI. However users will fail to install it for the lack of some files (Please refer to *Actual Result* section).

# Steps to Reproduce

`pip install simulaqron`

# Expected Result

The installed simulaqron and cqc are ready to pass `simulaqron.tests()` unit tests and the corrRNG example.

# Actual Result

```
$ pip install simulaqron

Collecting simulaqron
  Using cached https://files.pythonhosted.org/packages/81/9c/de06aa51efe8f57cfdd5df5a74eaaf1bb39500cfbbf93d2f9cb4b3423dbc/simulaqron-3.0.4.tar.gz
	ERROR: Complete output from command python setup.py egg_info:
	ERROR: Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "/tmp/pip-install-oc7t97tf/simulaqron/setup.py", line 21, in <module>
		with open("requirements.txt", 'r') as f:
	FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
	----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-oc7t97tf/simulaqron/
```

**Comment by AckslD** [comment]
@tai271828 Due to a typo only the `tar.gz` was uploaded to pypi but not the `.whl`. This is now fixed, see https://github.com/SoftwareQuTech/SimulaQron/pull/205 and the wheel is also on pypi. After some reading it seems to be some inconsistencies between including files in the wheel (bdist) and source (sdist), see https://stackoverflow.com/a/14159430/10566440. I tried to use the MANIFEST.in for the sdist, however this fails on the CI test on macos due to permission problems, as you can see in your pull request. Furthermore, it seems as if the command-line-interface is actually not properly working when using the `tar.gz` version of the package. An option would be to only use the wheel. I'm not sure if there are any disadvantages of this.

Anyway you can now try to install simulaqron again. Note that you might need to use the `--no-cache` flag.

**Comment by tai271828** [comment]
Thanks for the reply. To distribute the package in wheel format makes pretty much sense to me. It is an newer format.

Besides, I successfully install simulaqron (v3.0.4) (along with cqc v3.0.2) now. Thanks for re-distributing the package.
