### ISSUE TITLE
Where is virtualNodes.cfg?

### ISSUE THREAD

**Issue by samettonyali** [SoftwareQuTech/SimulaQron#245]
When I tried to run the example in SimulaQron/examples/nativeMode/corrRNG it ended up with an error saying  No such file or directory: '/home/samettonyali/Desktop/SimulaQron/simulaqron/config/virtualNodes.cfg'

Do you have any idea about where it's gone?

**Comment by AckslD** [comment]
Hi @samettonyali! Sorry for my late reply! I fixed the examples (see https://github.com/SoftwareQuTech/SimulaQron/pull/247) since they used the old way of configuration the network. However, note that the native mode is not the recommended way of programming simulaqron. The recommended way is using CQC (see https://github.com/SoftwareQuTech/CQC-Python) or the C or Rust library.
