### ISSUE TITLE
How to find amount of entanglement using CQC

### ISSUE THREAD

**Issue by ganeshmylavarapu-qp** [SoftwareQuTech/SimulaQron#265]
If I have to find the concurrence between two entangled particles, do we have any package in CQC to find the amount of entanglement like concurrence and fidelity??

**Comment by ganeshmylavarapu-qp** [comment]
If there are any examples you can provide, that would be great.

**Comment by AckslD** [comment]
@ganeshmylavarapu-qp Using the CQC interface one cannot directly access the qubit states (although there might be some extended feature in the future, see #209). This is because the CQC interface it meant to replicate the interface that would be used in a real quantum network in which case one cannot access quantum state. As for a real quantum network, one can on the other hand generate and measure a state many times to collect statistics and estimate fidelity or state. There is for example an example which shows how one can estimate the QBER (quantum-bit error rate) which you can find here https://github.com/SoftwareQuTech/CQC-Python/tree/master/examples/pythonLib/QBER. Given the QBER, one can estimate the fidelity.
